package iwium.rules

import iwium.*;
import robocode.*;

import iwium.MyRobot;

query "actionQuery"
    action: Action()
end

rule "scan"
    when
        robot: MyRobot()
    then
        robot.setTurnRadarRight(15);
        robot.execute();
end

rule "Scan for enemy"
    when
        e : ScannedRobotEvent()
        robot: MyRobot()
    then
        robot.setTurnRight(e.getBearing() + 90);

        double radarRotation = robot.getHeading() - robot.getRadarHeading() + e.getBearing();
        while (radarRotation >  180) radarRotation -= 360;
        while (radarRotation < -180) radarRotation += 360;

        robot.setTurnRadarRight(radarRotation);

        double rotation = robot.getHeading() - robot.getGunHeading() + e.getBearing();
        while (rotation >  180) rotation -= 360;
        while (rotation < -180) rotation += 360;

        robot.setTurnGunRight(rotation);

        System.err.println(robot.getHeading() - robot.getRadarHeading() + e.getBearing());
        System.err.println(robot.getHeading() - robot.getGunHeading() + e.getBearing());
        robot.setFire(3);

        robot.setAhead(10 * robot.getDirection());

        robot.execute();
end

rule "Robot has been hit"
    when
        e : HitByBulletEvent()
        robot: MyRobot();
    then
        double radarRotation = robot.getHeading() - robot.getRadarHeading() + e.getBearing();
        while (radarRotation >  180) radarRotation -= 360;
        while (radarRotation < -180) radarRotation += 360;

        robot.setTurnRadarRight(radarRotation);
        robot.setAhead(10 * robot.getDirection());

        robot.execute();
end

rule "Robot hit wall"
    salience 3
    activation-group "obstacles"
    when
        robot : MyRobot()
        HitWallEvent()
    then
        robot.switchDirection();
end

rule "Robot hit another robot"
    salience 2
    activation-group "obstacles"
    when
        robot : MyRobot()
        HitRobotEvent()
    then
        robot.switchDirection();
end

rule "Move forward"
    salience 1
    activation-group "motion"
    when
        robot : MyRobot();
    then
        robot.ahead(1 * robot.getDirection());
end